### ISSUE TITLE
Why is height: auto needed?

### ISSUE THREAD

**Issue by tvld** [Wlada/vue-carousel-3d#16]
To prevent my image to scale wrong, considering the aspect ratio of my images, I need to add:
```css
  .carousel-3d-slide {
      height: auto !important;
      background-color: rgba(0, 0, 0, 0.25) !important;
    }
```
Why is that? Am I missing something?

_Note: - the background opacity enables to use slider on dark backgrounds..._

**Comment by Wlada** [comment]
I'm not sure that I understand what is exactly a problem. Can you please create an example link?

**Comment by tvld** [comment]
Actually, it's been a while. What I recall, is that the challenge was to leave room for a caption. 
I now have:
```css
.carousel-3d-slide {
        background-color: rgba(0, 0, 0, 0.2) !important;
        height: calc(100% + 21px) !important;
    }
```

![screenshot from 2017-06-02 17-23-05](https://cloud.githubusercontent.com/assets/986182/26732594/5f34117c-47b8-11e7-8568-fcc709b8cc32.png)

Without the height, it looks like this:
![screenshot from 2017-06-02 17-26-03](https://cloud.githubusercontent.com/assets/986182/26732649/94211f1a-47b8-11e7-8beb-4bddd3760622.png)
