### ISSUE TITLE
Make responsive

### ISSUE THREAD

**Issue by tvld** [Wlada/vue-carousel-3d#6]
I've been really struggling to let the carousel fit properly on the various screens mobile - desktop. I suppose what is needed is a relative width property:
```html
  <carousel-3d class="slider"
      :width = "80%"
```

**Comment by tvld** [comment]
This will help a bit:

```css

.slider {
  @media screen and (min-width: 769px) {
      height: 220px;
  }
  @media screen and (max-width: 440px) {
      height: 140px;
  }
}
```
